List<String> arabicSurahNamesArr = [
  "الفاتحة",
  "البقرة",
  "آل عمران",
  "النساء",
  "المائدة",
  "الأنعام",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "يونس",
  "هود",
  "يوسف",
  "الرعد",
  "إبراهيم",
  "الحجر",
  "النحل",
  "الإسراء",
  "الكهف",
  "مريم",
  "طه",
  "الأنبياء",
  "الحج",
  "المؤمنون",
  "النور",
  "الفرقان",
  "الشعراء",
  "النمل",
  "القصص",
  "العنكبوت",
  "الروم",
  "لقمان",
  "السجدة",
  "الأحزاب",
  "سبأ",
  "فاطر",
  "يس",
  "الصافات",
  "ص",
  "الزمر",
  "غافر",
  "فصلت",
  "الشورى",
  "الزخرف",
  "الدخان",
  "الجاثية",
  "الأحقاف",
  "محمد",
  "الفتح",
  "الحجرات",
  "ق",
  "الذاريات",
  "الطور",
  "النجم",
  "القمر",
  "الرحمن",
  "الواقعة",
  "الحديد",
  "المجادلة",
  "الحشر",
  "الممتحنة",
  "الصف",
  "الجمعة",
  "المنافقون",
  "التغابن",
  "الطلاق",
  "التحريم",
  "الملك",
  "القلم",
  "الحاقة",
  "المعارج",
  "نوح",
  "الجن",
  "المزمل",
  "المدثر",
  "القيامة",
  "الإنسان",
  "المرسلات",
  "النبأ",
  "النازعات",
  "عبس",
  "التكوير",
  "الانفطار",
  "المطففين",
  "الانشقاق",
  "البروج",
  "الطارق",
  "الأعلى",
  "الغاشية",
  "الفجر",
  "البلد",
  "الشمس",
  "الليل",
  "الضحى",
  "الشرح",
  "التين",
  "العلق",
  "القدر",
  "البينة",
  "الزلزلة",
  "العاديات",
  "القارعة",
  "التكاثر",
  "العصر",
  "الهمزة",
  "الفيل",
  "قريش",
  "الماعون",
  "الكوثر",
  "الكافرون",
  "النصر",
  "المسد",
  "الإخلاص",
  "الفلق",
  "الناس"
];
List<String> englishSurahNamesArr = [
  "Al-Fatihah",
  "Al-Baqarah",
  "Ali 'Imran",
  "An-Nisa",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  "Al-Anfal",
  "At-Tawbah",
  "Yunus",
  "Hud",
  "Yusuf",
  "Ar-Ra'd",
  "Ibrahim",
  "Al-Hijr",
  "An-Nahl",
  "Al-Isra",
  "Al-Kahf",
  "Maryam",
  "Ta-Ha",
  "Al-Anbiya",
  "Al-Hajj",
  "Al-Mu'minun",
  "An-Nur",
  "Al-Furqan",
  "Ash-Shu'ara",
  "An-Naml",
  "Al-Qasas",
  "Al-'Ankabut",
  "Ar-Rum",
  "Luqman",
  "As-Sajdah",
  "Al-Ahzab",
  "Saba",
  "Fatir",
  "Ya-Sin",
  "As-Saffat",
  "Sad",
  "Az-Zumar",
  "Ghafir",
  "Fussilat",
  "Ash-Shura",
  "Az-Zukhruf",
  "Ad-Dukhan",
  "Al-Jathiyah",
  "Al-Ahqaf",
  "Muhammad",
  "Al-Fath",
  "Al-Hujurat",
  "Qaf",
  "Adh-Dhariyat",
  "At-Tur",
  "An-Najm",
  "Al-Qamar",
  "Ar-Rahman",
  "Al-Waqi'ah",
  "Al-Hadid",
  "Al-Mujadila",
  "Al-Hashr",
  "Al-Mumtahanah",
  "As-Saff",
  "Al-Jumu'ah",
  "Al-Munafiqun",
  "At-Taghabun",
  "At-Talaq",
  "At-Tahrim",
  "Al-Mulk",
  "Al-Qalam",
  "Al-Haqqah",
  "Al-Ma'arij",
  "Nuh",
  "Al-Jinn",
  "Al-Muzzammil",
  "Al-Muddaththir",
  "Al-Qiyamah",
  "Al-Insan",
  "Al-Mursalat",
  "An-Naba",
  "An-Nazi'at",
  "'Abasa",
  "At-Takwir",
  "Al-Infitar",
  "Al-Mutaffifin",
  "Al-Inshiqaq",
  "Al-Buruj",
  "At-Tariq",
  "Al-A'la",
  "Al-Ghashiyah",
  "Al-Fajr",
  "Al-Balad",
  "Ash-Shams",
  "Al-Layl",
  "Ad-Duha",
  "Ash-Sharh",
  "At-Tin",
  "Al-'Alaq",
  "Al-Qadr",
  "Al-Bayyinah",
  "Az-Zalzalah",
  "Al-'Adiyat",
  "Al-Qari'ah",
  "At-Takathur",
  "Al-'Asr",
  "Al-Humazah",
  "Al-Fil",
  "Quraysh",
  "Al-Ma'un",
  "Al-Kawthar",
  "Al-Kafirun",
  "An-Nasr",
  "Al-Masad",
  "Al-Ikhlas",
  "Al-Falaq",
  "An-Nas"
];
List<Map<String , dynamic>> suraNamesData = [
  { "number": 1, "englishName": "Al-Fatihah", "arabicName": "الفاتحة" },
  { "number": 2, "englishName": "Al-Baqarah", "arabicName": "البقرة" },
  { "number": 3, "englishName": "Aal-E-Imran", "arabicName": "آل عمران" },
  { "number": 4, "englishName": "An-Nisa", "arabicName": "النساء" },
  { "number": 5, "englishName": "Al-Maidah", "arabicName": "المائدة" },
  { "number": 6, "englishName": "Al-An'am", "arabicName": "الأنعام" },
  { "number": 7, "englishName": "Al-A'raf", "arabicName": "الأعراف" },
  { "number": 8, "englishName": "Al-Anfal", "arabicName": "الأنفال" },
  { "number": 9, "englishName": "At-Tawbah", "arabicName": "التوبة" },
  { "number": 10, "englishName": "Yunus", "arabicName": "يونس" },
  { "number": 11, "englishName": "Hud", "arabicName": "هود" },
  { "number": 12, "englishName": "Yusuf", "arabicName": "يوسف" },
  { "number": 13, "englishName": "Ar-Ra'd", "arabicName": "الرعد" },
  { "number": 14, "englishName": "Ibrahim", "arabicName": "إبراهيم" },
  { "number": 15, "englishName": "Al-Hijr", "arabicName": "الحجر" },
  { "number": 16, "englishName": "An-Nahl", "arabicName": "النحل" },
  { "number": 17, "englishName": "Al-Isra", "arabicName": "الإسراء" },
  { "number": 18, "englishName": "Al-Kahf", "arabicName": "الكهف" },
  { "number": 19, "englishName": "Maryam", "arabicName": "مريم" },
  { "number": 20, "englishName": "Ta-Ha", "arabicName": "طه" },
  { "number": 21, "englishName": "Al-Anbiya", "arabicName": "الأنبياء" },
  { "number": 22, "englishName": "Al-Hajj", "arabicName": "الحج" },
  { "number": 23, "englishName": "Al-Mu'minun", "arabicName": "المؤمنون" },
  { "number": 24, "englishName": "An-Nur", "arabicName": "النور" },
  { "number": 25, "englishName": "Al-Furqan", "arabicName": "الفرقان" },
  { "number": 26, "englishName": "Ash-Shu'ara", "arabicName": "الشعراء" },
  { "number": 27, "englishName": "An-Naml", "arabicName": "النمل" },
  { "number": 28, "englishName": "Al-Qasas", "arabicName": "القصص" },
  { "number": 29, "englishName": "Al-Ankabut", "arabicName": "العنكبوت" },
  { "number": 30, "englishName": "Ar-Rum", "arabicName": "الروم" },
  { "number": 31, "englishName": "Luqman", "arabicName": "لقمان" },
  { "number": 32, "englishName": "As-Sajda", "arabicName": "السجدة" },
  { "number": 33, "englishName": "Al-Ahzab", "arabicName": "الأحزاب" },
  { "number": 34, "englishName": "Saba", "arabicName": "سبإ" },
  { "number": 35, "englishName": "Fatir", "arabicName": "فاطر" },
  { "number": 36, "englishName": "Ya-Sin", "arabicName": "يس" },
  { "number": 37, "englishName": "As-Saffat", "arabicName": "الصافات" },
  { "number": 38, "englishName": "Sad", "arabicName": "ص" },
  { "number": 39, "englishName": "Az-Zumar", "arabicName": "الزمر" },
  { "number": 40, "englishName": "Ghafir", "arabicName": "غافر" },
  { "number": 41, "englishName": "Fussilat", "arabicName": "فصلت" },
  { "number": 42, "englishName": "Ash-Shura", "arabicName": "الشورى" },
  { "number": 43, "englishName": "Az-Zukhruf", "arabicName": "الزخرف" },
  { "number": 44, "englishName": "Ad-Dukhan", "arabicName": "الدخان" },
  { "number": 45, "englishName": "Al-Jathiya", "arabicName": "الجاثية" },
  { "number": 46, "englishName": "Al-Ahqaf", "arabicName": "الأحقاف" },
  { "number": 47, "englishName": "Muhammad", "arabicName": "محمد" },
  { "number": 48, "englishName": "Al-Fath", "arabicName": "الفتح" },
  { "number": 49, "englishName": "Al-Hujurat", "arabicName": "الحجرات" },
  { "number": 50, "englishName": "Qaf", "arabicName": "ق" },
  { "number": 51, "englishName": "Adh-Dhariyat", "arabicName": "الذاريات" },
  { "number": 52, "englishName": "At-Tur", "arabicName": "الطور" },
  { "number": 53, "englishName": "An-Najm", "arabicName": "النجم" },
  { "number": 54, "englishName": "Al-Qamar", "arabicName": "القمر" },
  { "number": 55, "englishName": "Ar-Rahman", "arabicName": "الرحمن" },
  { "number": 56, "englishName": "Al-Waqia", "arabicName": "الواقعة" },
  { "number": 57, "englishName": "Al-Hadid", "arabicName": "الحديد" },
  { "number": 58, "englishName": "Al-Mujadila", "arabicName": "المجادلة" },
  { "number": 59, "englishName": "Al-Hashr", "arabicName": "الحشر" },
  { "number": 60, "englishName": "Al-Mumtahanah", "arabicName": "الممتحنة" },
  { "number": 61, "englishName": "As-Saff", "arabicName": "الصف" },
  { "number": 62, "englishName": "Al-Jumu'a", "arabicName": "الجمعة" },
  { "number": 63, "englishName": "Al-Munafiqun", "arabicName": "المنافقون" },
  { "number": 64, "englishName": "At-Taghabun", "arabicName": "التغابن" },
  { "number": 65, "englishName": "At-Talaq", "arabicName": "الطلاق" },
  { "number": 66, "englishName": "At-Tahrim", "arabicName": "التحريم" },
  { "number": 67, "englishName": "Al-Mulk", "arabicName": "الملك" },
  { "number": 68, "englishName": "Al-Qalam", "arabicName": "القلم" },
  { "number": 69, "englishName": "Al-Haqqah", "arabicName": "الحاقة" },
  { "number": 70, "englishName": "Al-Ma'arij", "arabicName": "المعارج" },
  { "number": 71, "englishName": "Nuh", "arabicName": "نوح" },
  { "number": 72, "englishName": "Al-Jinn", "arabicName": "الجن" },
  { "number": 73, "englishName": "Al-Muzzammil", "arabicName": "المزمل" },
  { "number": 74, "englishName": "Al-Muddathir", "arabicName": "المدثر" },
  { "number": 75, "englishName": "Al-Qiyamah", "arabicName": "القيامة" },
  { "number": 76, "englishName": "Al-Insan", "arabicName": "الإنسان" },
  { "number": 77, "englishName": "Al-Mursalat", "arabicName": "المرسلات" },
  { "number": 78, "englishName": "An-Naba", "arabicName": "النبأ" },
  { "number": 79, "englishName": "An-Nazi'at", "arabicName": "النازعات" },
  { "number": 80, "englishName": "Abasa", "arabicName": "عبس" },
  { "number": 81, "englishName": "At-Takwir", "arabicName": "التكوير" },
  { "number": 82, "englishName": "Al-Infitar", "arabicName": "الإنفطار" },
  { "number": 83, "englishName": "Al-Mutaffifin", "arabicName": "المطففين" },
  { "number": 84, "englishName": "Al-Inshiqaq", "arabicName": "الانشقاق" },
  { "number": 85, "englishName": "Al-Buruj", "arabicName": "البروج" },
  { "number": 86, "englishName": "At-Tariq", "arabicName": "الطارق" },
  { "number": 87, "englishName": "Al-Ala", "arabicName": "الأعلى" },
  { "number": 88, "englishName": "Al-Ghashiyah", "arabicName": "الغاشية" },
  { "number": 89, "englishName": "Al-Fajr", "arabicName": "الفجر" },
  { "number": 90, "englishName": "Al-Balad", "arabicName": "البلد" },
  { "number": 91, "englishName": "Ash-Shams", "arabicName": "الشمس" },
  { "number": 92, "englishName": "Al-Lail", "arabicName": "الليل" },
  { "number": 93, "englishName": "Ad-Duha", "arabicName": "الضحى" },
  { "number": 94, "englishName": "Ash-Sharh", "arabicName": "الشرح" },
  { "number": 95, "englishName": "At-Tin", "arabicName": "التين" },
  { "number": 96, "englishName": "Al-Alaq", "arabicName": "العلق" },
  { "number": 97, "englishName": "Al-Qadr", "arabicName": "القدر" },
  { "number": 98, "englishName": "Al-Bayyina", "arabicName": "البينة" },
  { "number": 99, "englishName": "Az-Zalzalah", "arabicName": "الزلزلة" },
  { "number": 100, "englishName": "Al-Adiyat", "arabicName": "العاديات" },
  { "number": 101, "englishName": "Al-Qari'a", "arabicName": "القارعة" },
  { "number": 102, "englishName": "At-Takathur", "arabicName": "التكاثر" },
  { "number": 103, "englishName": "Al-Asr", "arabicName": "العصر" },
  { "number": 104, "englishName": "Al-Humazah", "arabicName": "الهمزة" },
  { "number": 105, "englishName": "Al-Fil", "arabicName": "الفيل" },
  { "number": 106, "englishName": "Quraish", "arabicName": "قريش" },
  { "number": 107, "englishName": "Al-Ma'un", "arabicName": "الماعون" },
  { "number": 108, "englishName": "Al-Kawthar", "arabicName": "الكوثر" },
  { "number": 109, "englishName": "Al-Kafirun", "arabicName": "الكافرون" },
  { "number": 110, "englishName": "An-Nasr", "arabicName": "النصر" },
  { "number": 111, "englishName": "Al-Masad", "arabicName": "المسد" },
  { "number": 112, "englishName": "Al-Ikhlas", "arabicName": "الإخلاص" },
  { "number": 113, "englishName": "Al-Falaq", "arabicName": "الفلق" },
  { "number": 114, "englishName": "An-Nas", "arabicName": "الناس" }
];